### ISSUE TITLE
Etusivulle komponentit josta selviää sivuston tarkoitus ja sisältö

### ISSUE THREAD

**Issue by jaakkokorhonen** [APIOps/portal#26]
joku mistä selviää heti kun sivulle tulee a) mitä se tekee b) näkee sisällön, mitä sieltä löytyy

**Comment by kyyberi** [comment]
This issue was moved to APIOps/apiops-meetup#4

**Comment by kyyberi** [comment]
This issue was moved to APIOps/apiops-meetup-website#10
