### ISSUE TITLE
More info in README.md

### ISSUE THREAD

**Issue by jjaone** [APIOps/portal#28]
Describe in the projects  GitHub Readme.md -file what the APIOps portal is, what is it used for, who are the intented users and how does it link to other national (Finland) API-communities and sites, like API:Suomi etc.

**Comment by kyyberi** [comment]
This issue was moved to APIOps/apiops-meetup#3

**Comment by kyyberi** [comment]
This issue was moved to APIOps/apiops-meetup-website#8
